apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app-newrelic-deployment
  labels:
    app: java-app-newrelic
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-app-newrelic
  template:
    metadata:
      labels:
        app: java-app-newrelic
    spec:
      containers:
      - name: java-app-newrelic
        image: zedahmed144/java:v5
        ports:
        - containerPort: 8080
        env:
        - name: JAVA_OPTS
          value: "-javaagent:/usr/local/newrelic/newrelic.jar"
