apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ready-api-prd
  name: ready-api-prd
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ready-api-prd
  template:
    metadata:
      labels:
        app: ready-api-prd
    spec:
      containers:
        - image: ready-api-prd
          name: ready-api-prd
          ports:
            - containerPort: 3000