apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- ingress.yml
- hpa.yml
namespace: prd-namespace
images:
- name: ready-api-prd
  newName: zedahmed144/ready-api
  newTag: 7b70abf7060197eb5d45e008f896a7f0642896a8
