apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- ingress.yml
- hpa.yml
namespace: prd-namespace
images:
- name: ready-api
  newName: zedahmed144/ready-api
  newTag: 59bb718210a3275ff4f6f8226c9f381a5b5c20e8
