apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ready-api-qa-hpa
  namespace: qa-namespace
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ready-api-qa
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
