apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- ingress.yml
- hpa.yml
namespace: qa-namespace
images:
- name: ready-api
  newName: zedahmed144/ready-api
  newTag: 2fb3c7cae1bf395f5a0b3ac60e507c272b94a4bb
- name: ready-api-qa
  newName: zedahmed144/ready-api
  newTag: 0e641a91a97933139d005df71a5a2483cffe9ed0
