apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- ingress.yml
- hpa.yml
namespace: qa-namespace
images:
- name: ready-api
  newName: zedahmed144/ready-api
  newTag: 4d68b71ceab3cc59fc30c4fbdcf484c8edb817b9
