apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- ingress.yml
- hpa.yml
namespace: qa-namespace
images:
<<<<<<< HEAD:infra/qa/kustomization.yml
- name: ready-api
  newName: zedahmed144/ready-api
  newTag: qa
=======
- name: argo-app
  newName: zedahmed144/argo-app
  newTag: dev
>>>>>>> 9c3bdf251183b793ae736077eeb85e26d240da75:infra/kustomization.yml
