apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- ingress.yml
- hpa.yml
namespace: qa-namespace
images:
- name: ready-api-qa
  newName: zedahmed144/ready-api
  newTag: 0e641a91a97933139d005df71a5a2483cffe9ed0
