apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
namespace: qa-namespace
images:
- name: ready-api-qa
  newName: zedahmed144/argo-app
  newTag: qa
