apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- ingress.yml
- hpa.yml
namespace: dev-namespace
images:
- name: ready-api
  newName: zedahmed144/ready-api
  newTag: 144c07c5751e9aa25a8b22a8f5157df9d09e0051
- name: ready-api-dev
  newName: zedahmed144/ready-api
  newTag: 9f6e5d672bc0afa86877dd6e6f89cc6365af5a4b
