apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- ingress.yml
namespace: dev-namespace
images:
- name: ready-api-dev
  newName: zedahmed144/argo-app
  newTag: 315df1d4d1bf4ca20d98ee1747220daf3114bd88
