name: gitops-CI

on:
  push:
    branches:
      - master
      - dev
      - qa
      - staging
      # Add other branches as needed

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set environment variables
        run: |
          echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
          echo "SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV
          echo "DATE_TAG=$(date +'%m-%d-%Y')" >> $GITHUB_ENV

      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with: 
          context: ./app
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/ready-api:latest
            ${{ secrets.DOCKER_USERNAME }}/ready-api:${{ env.BRANCH_NAME }}-${{ env.DATE_TAG }}
            ${{ secrets.DOCKER_USERNAME }}/ready-api:${{ env.SHORT_SHA }}

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Pull latest changes
        run: |
          git pull origin ${{ github.ref_name }}

      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v1
        with:
          kustomize-version: "3.6.1"

      - name: Update Kubernetes resources
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          BRANCH_NAME: ${{ github.ref_name }}
        run: |
          cd infra/${{ github.ref_name }}
          kustomize edit set image ready-api=$DOCKER_USERNAME/ready-api:${{ github.sha }}
          kustomize edit set image ready-api=$DOCKER_USERNAME/ready-api:${{ github.ref_name }}
          date >> log.txt
          echo "Deployment for $BRANCH_NAME on $(date)" >> log.txt
          cat kustomization.yml

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -am "rolling image to tag ${{ github.sha }}"

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GIT_HUB_TOKEN }}
          branch: ${{ github.ref_name }}
